import { test, expect, request, APIRequestContext } from '@playwright/test';
import {
  setAuthToken,
  setTenantPath,
  setLogonAs,
  getAuthToken,
  getTenantPath,
} from '../src/utils/tokenStore.js';
import { LOGON_AS, BASE_API_URL, EMAIL, PASSWORD } from '../src/utils/constants.js';

/* ---------------- UK NAME DATA ---------------- */

const UK_TASK_TYPES = [
  'Preparation',
  'Logistics',
  'Staffing',
  'Equipment Setup',
  'Venue Coordination',
  'Client Follow-up',
  'Inventory Check',
  'Cleanup Planning',
  'Security Briefing',
  'Transport Management',
];

/* ---------------- UTILS ---------------- */

function getCurrentDateTime() {
  return new Date()
    .toISOString()
    .replace('T', ' ')
    .substring(0, 19);
}

function generateTaskMasterName() {
  const taskType =
    UK_TASK_TYPES[Math.floor(Math.random() * UK_TASK_TYPES.length)];
  const currentDate = new Date().toISOString().split('T')[0];

  return `${taskType}_${currentDate}`;
}

/* ---------------- AUTH API ---------------- */

class AuthApi {
  private apiContext?: APIRequestContext;

  async init() {
    if (!this.apiContext) {
      this.apiContext = await request.newContext();
    }
  }

  async fetchTenantOptions() {
    await this.init();
    const response = await this.apiContext!.get(
      `${BASE_API_URL}/api/tenant-options`,
      { headers: { 'Content-Type': 'application/json' } }
    );

    expect(response.ok()).toBeTruthy();
    const body = await response.json();
    return body.data || [];
  }

  async login(email: string, password: string, tenantName: string) {
    await this.init();
    const response = await this.apiContext!.post(
      `${BASE_API_URL}/api/login`,
      {
        headers: { 'Content-Type': 'application/json' },
        data: { email, password, tenant_name: tenantName },
      }
    );

    expect(response.ok()).toBeTruthy();
    const body = await response.json();

    expect(body.token).toBeTruthy();
    expect(body.tenant_cname).toBeTruthy();
    expect(body.logon_as).toBeTruthy();

    return body;
  }
}

/* ---------------- TASKMASTER API ---------------- */

class TaskMasterApi {
  private apiContext?: APIRequestContext;

  async init() {
    if (!this.apiContext) {
      this.apiContext = await request.newContext();
    }
  }

  async createTaskMaster(payload: any) {
    await this.init();

    const token = getAuthToken();
    const tenantPath = getTenantPath();

    expect(token).toBeTruthy();
    expect(tenantPath).toBeTruthy();

    const response = await this.apiContext!.post(
      `${BASE_API_URL}/${tenantPath}/api/${LOGON_AS}/taskmaster`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        data: payload,
      }
    );

    expect(response.ok()).toBeTruthy();
    return await response.json();
  }
}

/* ---------------- TEST ---------------- */

test('API only: login and create TaskMaster', async () => {
  const authApi = new AuthApi();

  // 1️⃣ Fetch tenant (Dream Events fix applied)
  const tenants = await authApi.fetchTenantOptions();

  const normalize = (v: string) => v.toLowerCase().replace(/\s+/g, '');

  const tenant = tenants.find(
    (t: any) => normalize(t.optionlabel) === normalize('Dream Events')
  );

  if (!tenant) {
    throw new Error('Tenant "Dream Events" not found');
  }

  // 2️⃣ Login
  const loginResponse = await authApi.login(
    EMAIL,
    PASSWORD,
    tenant.optionvalue
  );

  setAuthToken(loginResponse.token);
  setTenantPath(loginResponse.tenant_cname);
  setLogonAs(loginResponse.logon_as);

  expect(getAuthToken()).toBeTruthy();
  expect(getTenantPath()).toBeTruthy();

  // 3️⃣ Generate meaningful UK TaskMaster name
  const taskMasterName = generateTaskMasterName();
  const dateTime = getCurrentDateTime();

  // 4️⃣ Payload (NO field skipped)
  const payload = {
    taskmaster_num: '00000000000',
    custom: {
      taskmaster_name: taskMasterName,
      taskmaster_category: 640,
      taskmaster_description: 'AutoGenerated',
      taskmaster_priority: 654,
      taskmaster_dueday: '2',
      ownerid: 6,
      createtime: dateTime,
      modifiedtime: dateTime,
      assign_to: 'Sonam Burbure',
    },
    source: 'web',
    status: '1',
  };

  console.log('Final TaskMaster Payload:', JSON.stringify(payload, null, 2));

  // 5️⃣ Create TaskMaster
  const taskMasterApi = new TaskMasterApi();
  const response = await taskMasterApi.createTaskMaster(payload);

  console.log('Create TaskMaster API response:', response);

  // 6️⃣ Assertions
  const taskMaster = Array.isArray(response) ? response[0] : response;

  expect(taskMaster).toBeTruthy();
  expect(taskMaster.taskmasterid).toBeTruthy();
  expect(typeof taskMaster.taskmasterid).toBe('number');

  console.log('Created TaskMaster ID:', taskMaster.taskmasterid);
});
